services:
  traefik:
    image: traefik:v3
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme.json:/acme.json
      - ./acme-zerossl.json:/acme-zerossl.json
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=florian.bufler@fbufler.cloud
      - --certificatesresolvers.letsencrypt.acme.storage=/acme.json
      - --certificatesresolvers.zerossl.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.zerossl.acme.email=florian.bufler@fbufler.cloud
      - --certificatesresolvers.zerossl.acme.storage=/acme-zerossl.json
      - --certificatesresolvers.zerossl.acme.caserver=https://acme.zerossl.com/v2/DV90
      - --certificatesresolvers.zerossl.acme.eab.kid=${ZEROSSL_KID}
      - --certificatesresolvers.zerossl.acme.eab.hmacencoded=${ZEROSSL_HMAC_KEY}
    networks:
      - web

networks:
  web:
    external: true
