services:
  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=fbufler
      - GF_SECURITY_ADMIN_PASSWORD=changeme
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`grafana.fbufler.cloud`)
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.tls.certresolver=letsencrypt
      - traefik.http.services.grafana.loadbalancer.server.port=3000
      - traefik.docker.network=web
    networks:
      - web
      - monitoring

volumes:
  prometheus_data:
  grafana_data:

networks:
  web:
    external: true
  monitoring:
    internal: true
