services:
  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - monitoring

  loki:
    image: grafana/loki:latest
    restart: always
    user: root
    volumes:
      - ./loki/config.yml:/etc/loki/config.yml
      - loki_data:/loki
    command: -config.file=/etc/loki/config.yml
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:latest
    restart: always
    volumes:
      - ./promtail/config.yml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitoring

  tempo:
    image: grafana/tempo:2.6.1
    restart: always
    user: root
    volumes:
      - ./tempo/config.yml:/etc/tempo.yml
      - tempo_data:/var/tempo
    command: -config.file=/etc/tempo.yml
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    restart: always
    pid: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --path.rootfs=/rootfs
      - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=fbufler
      - GF_SECURITY_ADMIN_PASSWORD=changeme
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`grafana.fbufler.cloud`)
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.tls.certresolver=letsencrypt
      - traefik.http.services.grafana.loadbalancer.server.port=3000
      - traefik.docker.network=web
    networks:
      - web
      - monitoring

volumes:
  prometheus_data:
  loki_data:
  tempo_data:
  grafana_data:

networks:
  web:
    external: true
  monitoring:
    external: true
